name: Test

on:
  pull_request:

jobs:
  pass:
    name: Pass
    runs-on: ubuntu-20.04

    steps:
      - name: Inform on PR that Pass
        uses: hussedev/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running***
            PASS

  fail:
    name: Fail
    runs-on: ubuntu-20.04

    steps:
      - name: Inform on PR that Fails
        uses: hussedev/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          status: 'failure'
          message-failure: |
            ***Running***
            FAIL
