name: Test

on:
  pull_request:

jobs:
  pass:
    name: Pass
    runs-on: ubuntu-20.04

    steps:
      - name: Inform on PR that Pass
        uses: hussedev/add-pr-comment@make_check_fail
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ***Running***
            PASS

  fail:
    name: Fail
    runs-on: ubuntu-20.04

    steps:
      - name: Inform on PR that Fails
        uses: hussedev/add-pr-comment@make_check_fail
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: 'failure'
          message-failure: |
            ***Running***
            FAILED
